# Always validate the PR title AND all the commits
titleAndCommits: true
# allowRevertCommits: true
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - change